## Import thư viện numpy

In [2]:
import numpy as np

## Tạo mảng

In [36]:
# Tạo mảng chứa số lượng của 1 loại sản phẩm bán ra trong các tháng (từ tháng 1 - tháng 5)
arr1 = np.array([120, 85, 230, 150, 60])
print(arr1)
arr1

[120  85 230 150  60]


array([120,  85, 230, 150,  60])

In [3]:
arr1.dtype

dtype('int64')

In [4]:
type(arr1)

numpy.ndarray

In [ ]:
# Đối tượng mảng có 2 thành phần : thuộc tính , phương thức(hàm)
# Truy xuất:
# tenmang.thuoctinh
# tenmang.phuongthuc()

## Thuộc tính của mảng

In [5]:
type(arr1)

numpy.ndarray

In [6]:
# kiểu dữ liệu của các phần tử trong mảng
arr1.dtype

dtype('int64')

In [7]:
# đếm số phần tử trong mảng
arr1.size 

5

In [8]:
# mảng 1 chiều, có 5 phần tử
arr1.shape

(5,)

In [9]:
# mảng 1 chiều
arr1.ndim

1

In [10]:
# kich thước 1 phần tử 
arr1.itemsize 

8

In [11]:
# kich thước của mảng
arr1.nbytes

40

In [13]:
# Pt tìm pt lớn nhất
print(arr1.max())

230


# Ví dụ khác


In [16]:
arr2 = np.array([[120], [85], [230], [150], [60]])
arr2
arr2.shape



(5, 1)

In [4]:
a = np.array([[1,2,3],[3,4,5]])
a

array([[1, 2, 3],
       [3, 4, 5]])

In [5]:
a.shape

(2, 3)

#### Hướng dẫn  HV tạo mảng từ tuple , có sử dụng dtype với nhiều giá trị tham số khác nhau 

In [11]:
# Tạo mảng chứa tuổi của 5 hv từ tuple 
arr_age = np.array((21, 25, 29, 30, 32),dtype='i1')
arr_age

array([21, 25, 29, 30, 32], dtype=int8)

In [9]:
arr_age.dtype

dtype('int8')

In [12]:
# Tạo một mảng lưu trữ chiều cao của 5 hv 
arr_height = np.array([160.5, 165.7, 170.2, 175.3, 180.0])
arr_height.nbytes

40

In [13]:
arr_height.dtype

dtype('float64')

In [14]:
# Tạo một mảng lưu trữ chiều cao của 5 hv 
# với giá trị 
# - kiểu số nguyên có dấu 2 byte (dtype='i2')
# - số nguyên không dấu 1 byte (dtype='u1') 
# số thập phân 2 byte (dtype = 'float16')
arr_height = np.array([160.5, 165.7, 170.2, 175.3, 180.0], dtype='f4') 
arr_height

array([160.5, 165.7, 170.2, 175.3, 180. ], dtype=float32)

In [15]:
arr_height.dtype

dtype('float32')

## Tạo mảng từ các hàm tiện ích
#### Hướng dẫn HV tạo mảng từ các hàm tiện ích

In [16]:
# tạo mảng có 10 phần tử có giá trị 0
arr0 = np.zeros((10,),dtype=int)
arr0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
# tạo mảng có 10 phần tử có giá trị 1
arr_1 = np.ones((10,),dtype=int)
print(arr_1)

[1 1 1 1 1 1 1 1 1 1]


In [18]:
# tạo mảng có 10 phần tử có giá trị 4
arr2 = np.full((10,), fill_value=4)
print(arr2)

[4 4 4 4 4 4 4 4 4 4]


In [19]:
# tạo mảng có 10 phần tử từ 0 đến 9
arr3 = np.arange(10) # arange(0,10,1)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
# tạo mảng có 9 phần tử từ 1 đến 9
arr4 = np.arange(1, 10)
print(arr4)

[1 2 3 4 5 6 7 8 9]


In [21]:
# tạo mảng có các phần tử chẵn < 10
arr5 = np.arange(0,10,2)
print(arr5)

[0 2 4 6 8]


In [22]:
# tạo mảng có các phần tử 10->1
arr5 = np.arange(10,0,-1)
print(arr5)

[10  9  8  7  6  5  4  3  2  1]


In [ ]:
# linspace(start,stop,num,endpoint)
# endpoint = True => bins= (stop - start)/(num - 1)
# endpoint = False => bins= (stop - start)/(num)

In [23]:
# Tạo mảng có 15 phần tử số nguyên cách đều từ 2 đến 30 (bao gồm 30)
arr6 = np.linspace(2, 30, 15,endpoint=True)
print(arr6)

[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30.]


In [24]:
arr6 = np.linspace(1, 10, 15,endpoint=False)
print(arr6)

[1.  1.6 2.2 2.8 3.4 4.  4.6 5.2 5.8 6.4 7.  7.6 8.2 8.8 9.4]


In [25]:
# Tạo mảng có 5 phần tử cách đều từ 2 đến 10 (bao gồm 10)
arr7 = np.linspace(2, 10, 5,endpoint=True)
print(arr7)

[ 2.  4.  6.  8. 10.]


In [39]:
# Tạo mảng có 5 phần tử cách đều từ 2 đến 10 (không bao gồm 10)
arr8 = np.linspace(2, 10, 5, endpoint=False, retstep = True)
print(arr8)

(array([2. , 3.6, 5.2, 6.8, 8.4]), np.float64(1.6))


In [27]:
# tạo mảng ngẫu nhiên 4 phần tử từ 0 đến 1 (không bao gồm 1)
arr9 = np.random.rand(4)
print(arr9)

[0.76067215 0.29486124 0.46562455 0.98372943]


In [28]:
# tạo mảng ngẫu nhiên 10 phần tử từ 0 đến 5
arr10 = np.random.randint(6,size=10)
print(arr10)

[5 1 3 5 2 5 1 5 0 3]


In [33]:
np.random.seed(8)
arr10 = np.random.randint(low=1,high=6, size=10)
print(arr10)

[4 5 2 2 3 1 4 1 1 5]


In [30]:
# tạo mảng ngẫu nhiên 5 phần tử từ 0 đến 2
np.random.seed(8)
arr11 = np.random.randint(0,3, 5)
print(arr11)

[0 1 1 1 2]


In [34]:
#### Tạo mảng từ tập tin heights.txt
heights = np.genfromtxt('heights.txt', delimiter=',') # chiều cao các vận động viên bóng chày (tính theo inch)
print(heights[:10])
print(heights.size)

[74. 74. 72. 72. 73. 69. 69. 71. 76. 71.]
1015


## Truy xuất
### Truy xuất 1 phần tử

In [37]:
arr1

array([120,  85, 230, 150,  60])

In [40]:
arr1[0]  # giá trị phần tử đầu tiên

np.int64(120)

In [41]:
arr1[-1] # giá trị phần tử cuối cùng

np.int64(60)

In [42]:
arr1[3] # giá trị phần tử tại index 3

np.int64(150)

In [43]:
heights[1014]

np.float64(73.0)

In [44]:
heights[-1]

np.float64(73.0)

### Truy xuất nhiều phần tử theo danh sách index

In [45]:
arr1

array([120,  85, 230, 150,  60])

In [46]:
# Giá trị phần tử ở vị trí index 0,1,4
lst_index = [0,1,4]
arr1[lst_index]

array([120,  85,  60])

### Truy xuất nhiều phần tử theo slice

In [47]:
#Hiển thị giá trị 3 phần tử đầu index 0,1,2
arr1[:3]  

array([120,  85, 230])

In [48]:
#Hiển thị giá trị 2 phần tử cuối -2,-1
arr1[-2:]

array([150,  60])

In [49]:
#Hiển thị giá trị phần tử vị trí index lẻ
arr1[1::2]

array([ 85, 150])

In [50]:
# Hiển thị mảng đảo ngược của arr1
arr1[::-1]

array([ 60, 150, 230,  85, 120])

### Truy xuất phần tử theo điều kiện

In [51]:
arr1

array([120,  85, 230, 150,  60])

In [52]:
arr1 > 100

array([ True, False,  True,  True, False])

In [54]:
# Hiển thị các phần tử có các giá trị >100
arr1[arr1 > 100]

array([120, 230, 150])

### Truy xuất phần tử theo nhiều điều kiện

In [55]:
# Hiển thị các phần tử có giá trị từ 100 đến 200
arr1[(arr1 >= 100) & (arr1 <= 200)] # and

array([120, 150])

In [56]:
# Hiển thị các phần tử có giá trị nhỏ hơn 100 hoặc lớn hơn 200
arr1[(arr1 < 100) | (arr1 > 200)] # or

array([ 85, 230,  60])

In [57]:
# Hiển thị các phần tử có giá trị không lớn hơn 100
arr1[~(arr1 > 100)]# not

array([85, 60])

### Truy xuất phần tử theo điều kiện với np.where

In [ ]:
arr1[arr1 > 100]

In [ ]:
arr1

In [ ]:
# Index của các phần tử có giá trị > 100?
idx = np.where(arr1 > 100)
idx

In [ ]:
# Hiển thị các phần tử có giá trị > 100
arr1[idx]

## Thêm, xóa, sửa dữ liệu mảng
### Thêm phần tử vào cuối mảng

In [ ]:
arr1

In [ ]:
np.concatenate ([arr1,[200]])

In [ ]:
arr1

In [ ]:
# Thêm giá trị vào cuối mảng arr1
arr1 = np.concatenate ([arr1, [200]])
arr1

In [ ]:
# thêm nhiều giá trị vào cuối mảng arr1
arr1= np.concatenate([arr1, [170, 95, 210]])
arr1

### Chèn phần tử vào mảng ở vị trí xác định, sử dụng np.insert()

In [ ]:
arr1 = np.array([120, 85, 230, 150, 60])
arr1

In [ ]:
# Chèn 1 phần tử vào mảng
arr4 = np.insert(arr1, 4, 100)
arr4

In [ ]:
# Chèn nhiều phần tử vào mảng
arr4 = np.insert(arr1, 5, [80, 70])
arr4

In [ ]:
arr1

In [ ]:
# Chèn nhiều phần tử vào mảng vào nhiều vị trí
arr4 = np.insert(arr1, [1,4], [80, 70])
arr4

### Xóa phần tử
Trước khi xóa cột, bạn nên xem xét cẩn thận và đảm bảo rằng việc xóa không làm mất đi thông tin quan trọng và không ảnh hưởng đến mục tiêu của bạn trong việc phân tích hoặc xử lý dữ liệu.

In [ ]:
arr1 = np.array([120, 85, 230, 150, 60])
arr1

In [ ]:
# Xóa phần tử ở vị trí 1
np.delete(arr1, 1)

In [ ]:
arr1

In [ ]:
# Xóa phần tử ở vị trí 0,2,3
np.delete(arr1, [0,2,3])

### Sửa giá trị phần tử trong mảng
#### Sửa 1 phần tử

In [ ]:
arr1 = np.array([120, 85, 230, 150, 60])
arr1

In [ ]:
arr1[2]

In [ ]:
# Sửa giá trị ở vị trí 2
arr1[2] = 80
arr1

#### Sửa nhiều phần tử

In [ ]:
arr1

In [ ]:
arr1[arr1 < 100]

In [ ]:
# Sửa các giá trị nhỏ hơn 100 là 100
arr1[arr1 < 100] = 100
arr1

In [ ]:
# Sửa các giá trị bằng 100 là 1,2,3
arr1[arr1 == 100] = [1,2,3]
arr1


In [ ]:
arr1[[2,4]]

In [ ]:
# Sửa giá trị ở vị trí 2,4
arr1[[2,4]] = [90, 85]
arr1

## Phép toán số học trên mảng

In [ ]:
arr1 = np.array([120, 85, 230, 150, 60])
arr1

In [ ]:
arr1 + 10

In [ ]:
arr1 - 20

In [ ]:
arr1 * 3

In [ ]:
arr1 /2

In [ ]:
arr_a = np.array([110, 50, 60, 80, 100])
arr_b = np.array([90, 65, 75, 85, 105])

In [ ]:
arr_a + arr_b

## Các hàm toán học

In [ ]:
arr3 = np.array([1,4,9,16,25])
arr4 = np.array([1,8,27,64,125])

In [ ]:
arr3 ** 2

In [ ]:
# Bình phương
np.square(arr3)

In [ ]:
# Căn bậc 2
np.sqrt(arr3)

In [ ]:
# căn bậc 3
np.cbrt(arr4)

In [ ]:
arr5 = np.array([4, -2, 6, -9, 3])
# trị tuyệt đối
np.abs(arr5)

In [ ]:
arr6 = np.array([5.423, 8.976, 4.3584, 7.6582])
arr6

In [ ]:
np.round(arr6, 1)

In [ ]:
np.round(arr6)

## Các hàm thống kê

In [ ]:
arr1 = np.array([120, 85, 230, 150, 60,200,10])
arr1

In [ ]:
# Tổng tất cả phần tử trong mảng
np.sum(arr1)

In [ ]:
arr1.sum()

In [ ]:
sum(arr1)

In [ ]:
# phần tử nhỏ nhất
np.min(arr1)

In [ ]:
arr1.min()

In [ ]:
min(arr1)

In [ ]:
# phần tử lớn nhất
np.max(arr1)

In [ ]:
# giá trị trung bình
np.mean(arr1)

In [ ]:
arr1.mean()

In [ ]:
arr1

In [ ]:
# giá trị trung vị
#120,  85, 230, 150,  60, 200 10 =>10 60 85 120 150 200 230
np.median(arr1)

In [ ]:
# độ lệch chuẩn
np.std(arr1)

In [ ]:
arr1.std()

In [ ]:
# phương sai
np.var(arr1)

In [ ]:
# tứ phân vị
print('Q1 =', np.quantile(arr1, 0.25))
print('Q2 =', np.quantile(arr1, 0.5))
print('Q3 =', np.quantile(arr1, 0.75))

## Sắp xếp mảng

In [ ]:
# Sắp xếp tăng dần
np.sort(arr1)

In [ ]:
arr1

In [ ]:
arr1.sort()

In [ ]:
arr1

In [ ]:
# Sắp xếp giảm dần
np.sort(arr1)[::-1]

# Chuyển đổi KDL

In [ ]:
arr1 = np.array([120, 85, 230, 150, 60,200],dtype=float)
arr1

In [ ]:
arr1.dtype

In [ ]:
arr1 = arr1.astype(int)

In [ ]:
arr1