## Import thư viện

In [1]:
import numpy as np

## Phần 1: Tạo mảng
### Tạo mảng 1 chiều

In [2]:
# 1. Tạo một mảng numpy 1 chiều even_numbers chứa 10 phần tử là các số chẵn trong phạm vi [2,20] 
even_numbers = np.arange(2,21,2)
print(even_numbers)

[ 2  4  6  8 10 12 14 16 18 20]


In [3]:
# 2. Tạo một mảng numpy 1 chiều chứa 5 phần tử là các số chia cho 5 dư 1 (số nguyên có dạng 5x + 1) trong phạm vi [1,21].
arr2 = np.arange(1,22,5)
arr2

array([ 1,  6, 11, 16, 21])

In [4]:
# 3.Tạo 1 mảng 1 chiều gồm 11 phần tử cách đều nhau từ 0 đến 1
# Cho biết khoảng cách giữa các giá trị retstep
arr3 = np.linspace(0, 1, 11, endpoint = True, retstep = True)
arr3


(array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]),
 np.float64(0.1))

In [5]:
# 4.Tạo 1 mảng 1 chiều gồm 5 phần tử là các số nguyên ngẫu nhiên từ 1 đến 20
np.random.seed(5)
arr4 = np.random.randint(1,21, size = 5)
print(arr4)

[ 4 15 16  7 17]


In [6]:
# 5.Tạo mảng numpy 1 chiều chứa 10 phần tử với các phần tử ở index chẵn là 0 và ở index lẻ là số lẻ


In [7]:
# 6.Tạo 1 mảng 1 chiều gồm 10 phần tử có các phần tử ở index [0,3,6,9] là 3 và các phần tử còn lại là 1 


In [8]:
# 7. Tạo 1 mảng 1 chiều gồm 5 phần tử là các giá trị ngẫu nhiên (không trùng nhau) chia hết cho 3 và nhỏ hơn 30
np.random.seed(5)

# Bước 1: Tạo mảng gồm các phần tử nhỏ hơn 30 và chia hết cho 3
arr=np.arange(0, 30,3)
print(arr)
# Bước 2: Tạo mảng gồm 5 phần tử ngẫu nhiên (không trùng nhau) từ mảng vừa tạo
result = np.random.choice(arr, 5, replace = False)
print(result)

[ 0  3  6  9 12 15 18 21 24 27]
[27 15  6 12 21]


### Tạo mảng 2 chiều

In [9]:
# 8.Tạo mảng 2 chiều (3x4) arr_2d với các số chẵn ngẫu nhiên (không trùng nhau) < 50
np.random.seed(1)
arr= np.arange(0, 50, 2)
arr_2d = np.random.choice(arr, (3,4), replace = False)
arr_2d

array([[28, 26, 34,  6],
       [42, 20, 36, 38],
       [ 8,  4, 40, 12]])

In [10]:
# 9. Tạo một mảng numpy 2 chiều (6x6) với các giá trị biên là 1 và các giá trị còn lại là 0
# Tạo một mảng 2 chiều (6x6) với tất cả giá trị là 1
## Sau khi tạo mảng có giá trị 1, cập nhật các giá trị 0 theo yêu cầu
arr_b = np.ones((6,6))
arr_b[1:-1,1:-1] = 0
print(arr_b)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [11]:
# 10. Tạo một mảng numpy 2 chiều (3x3) với các giá trị trên đường chéo chính là 1 và các giá trị còn lại là 0 
np.eye(3)
# mảng kết quả


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# Cách 2
a = np.ones(3)
np.diag(a)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
x = np.random.randint(1,10,(4,4))
x

array([[3, 5, 8, 8],
       [2, 8, 1, 7],
       [8, 7, 2, 1],
       [2, 9, 9, 4]], dtype=int32)

In [14]:
y = np.diag(x)
y

array([3, 8, 2, 4], dtype=int32)

In [15]:
np.diag(y)

array([[3, 0, 0, 0],
       [0, 8, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 4]], dtype=int32)

## Phần 2: Truy xuất
### Mảng 1 chiều
Từ mảng even_numbers đã tạo ở câu 1. Hãy thực hiện các truy xuất sau:

In [16]:
even_numbers

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [17]:
# 11. Truy xuất giá trị phần tử thứ 3 của mảng even_numbers
element3 =  even_numbers[2]
print(element3)

6


In [18]:
# 12. Truy xuất các phần tử từ vị trí thứ 2 đến vị trí thứ 4 (bao gồm cả vị trí thứ 4) của mảng even_numbers
position2to4 =  even_numbers[1:4]
print(position2to4)

[4 6 8]


In [19]:
# 13.Truy xuất các phần tử lớn hơn 10 từ mảng even_numbers
arr_larger_than_10 = even_numbers[even_numbers >10]
print(arr_larger_than_10)

[12 14 16 18 20]


In [20]:
# 14. Truy xuất các phần tử chia hết cho 3 từ mảng even_numbers và lớn hơn 10
newArray = even_numbers [(even_numbers%3==0)&(even_numbers >10)]
print(newArray)

[12 18]


### Mảng 2 chiều
Từ mảng arr_2d đã tạo ở câu 8. Hãy thực hiện các truy xuất sau:

In [21]:
arr_2d

array([[28, 26, 34,  6],
       [42, 20, 36, 38],
       [ 8,  4, 40, 12]])

In [22]:
# 15.Cho biết phần tử ở hàng thứ 2 và cột thứ 3 của mảng arr_2d
arr_2d[2,3] 


np.int64(12)

In [23]:
# 16. Hiển thị toàn bộ hàng 1 của mảng arr_2d
arr_2d[1,:]

array([42, 20, 36, 38])

In [24]:
# 17. Hiển thị toàn bộ cột 2 của mảng arr_2d
arr_2d[:,2]

array([34, 36, 40])

In [25]:
# 18. Lọc các phần tử trong mảng arr_2d lớn hơn 30
arr_2d[arr_2d > 30]

array([34, 42, 36, 38, 40])

In [26]:
# 19. Lọc ra các dòng có phần tử ở cột thứ 2 trong mảng arr_2d chia hết cho 4
arr_2d[arr_2d[:,2] % 4 == 0]

array([[42, 20, 36, 38],
       [ 8,  4, 40, 12]])

In [27]:
# 20. Cho biết các giá trị trong mảng arr_2d nằm trong khoảng từ [10, 30]
arr_2d[(arr_2d >=10) & (arr_2d <=30)]

array([28, 26, 20, 12])

## Phần 3: Thêm, xóa, sửa phần tử trong mảng
### Mảng 1 chiều
Từ mảng even_numbers đã tạo ở câu 1. Hãy thực hiện các yêu cầu sau:

In [28]:
even_numbers

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [29]:
# 21. Thêm giá trị 22 vào cuối mảng 
even_numbers = np.concatenate([even_numbers, [22]])
even_numbers

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [30]:
# 22. Thêm giá trị 30 vào vị trí thứ 5 của mảng
even_numbers = np.insert(even_numbers, 5, 30)
even_numbers

array([ 2,  4,  6,  8, 10, 30, 12, 14, 16, 18, 20, 22])

In [31]:
# 23. Tạo mảng temp là mảng even_numbers đã xóa giá trị tại vị trí thứ 7 
temp = np.delete(even_numbers,7)
temp

array([ 2,  4,  6,  8, 10, 30, 12, 16, 18, 20, 22])

In [32]:
# 24. Tạo mảng temp là mảng even_numbers đã xóa giá trị 8
temp = np.delete(even_numbers,np.where(even_numbers == 8))
temp

array([ 2,  4,  6, 10, 30, 12, 14, 16, 18, 20, 22])

In [33]:
# 25. Thay đổi các giá trị < 10 từ mảng even_numbers thành 10
even_numbers[even_numbers < 10] = 10
even_numbers

array([10, 10, 10, 10, 10, 30, 12, 14, 16, 18, 20, 22])

### Mảng 2 chiều
Từ mảng arr_2d đã tạo ở câu 8. Hãy thực hiện các yêu cầu sau:

In [41]:
arr_2d

array([[28, 26, 34,  6],
       [42, 20, 36, 38],
       [ 8,  4, 40, 12]])

In [49]:
# 26. Thêm hàng mới [10, 16, 20, 24] vào cuối mảng arr_2d
new_row = [[10, 16, 20, 24]]
arr_2d = np.concatenate([arr_2d, new_row], axis = 0)
arr_2d

array([[28, 26, 34,  6],
       [42, 20, 36, 38],
       [ 8,  4, 40, 12],
       [10, 16, 20, 24]])

In [51]:
# 27. Thêm cột mới [50, 60, 70, 80] vào cuối mảng arr_2d
new_column = np.array([[50, 60, 70, 80]])
arr_2d = np.concatenate([arr_2d, new_column.T], axis = 1) 
arr_2d

array([[28, 26, 34,  6, 50],
       [42, 20, 36, 38, 60],
       [ 8,  4, 40, 12, 70],
       [10, 16, 20, 24, 80]])

In [53]:
# 28. Tạo mảng temp là mảng arr_2d đã xóa hàng thứ 2
temp_arr = np.delete(arr_2d, 2, axis = 0)
temp_arr

array([[28, 26, 34,  6, 50],
       [42, 20, 36, 38, 60],
       [10, 16, 20, 24, 80]])

In [54]:
# 29. Tạo mảng temp là mảng arr_2d đã xóa cột thứ 3
temp_arr2 = np.delete(arr_2d, 3, axis = 1)
temp_arr2

array([[28, 26, 34, 50],
       [42, 20, 36, 60],
       [ 8,  4, 40, 70],
       [10, 16, 20, 80]])

In [55]:
# 30. Sửa giá trị tại dòng 1, cột 2 thành 30
arr_2d[1,2] = 30
arr_2d

array([[28, 26, 34,  6, 50],
       [42, 20, 30, 38, 60],
       [ 8,  4, 40, 12, 70],
       [10, 16, 20, 24, 80]])

In [56]:
# 31. Sửa các giá trị lớn hơn 10 và nhỏ hơn 20 trong arr_2d thành 20
arr_2d [(arr_2d > 10) & (arr_2d < 20)] = 20
arr_2d

array([[28, 26, 34,  6, 50],
       [42, 20, 30, 38, 60],
       [ 8,  4, 40, 20, 70],
       [10, 20, 20, 24, 80]])

In [59]:
# 32. Sửa các giá trị nhỏ hơn 30 và không chia hết cho 4 tại dòng đầu tiên trong arr_2d thành 30
arr_2d [(arr_2d [0, : ] < 30) & (arr_2d [0, : ] < 30) % 4 != 0] = 30
arr_2d

IndexError: boolean index did not match indexed array along axis 0; size of axis is 4 but size of corresponding boolean axis is 5