## Import thư viện

In [2]:
import numpy as np

## Phần 1: Tạo mảng
### Tạo mảng 1 chiều

In [2]:
# 1. Tạo một mảng numpy 1 chiều even_numbers chứa 10 phần tử là các số chẵn trong phạm vi [2,20] 
even_numbers = np.arange(2,21,2)
even_numbers

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [4]:
# 2. Tạo một mảng numpy 1 chiều chứa 5 phần tử là các số chia cho 5 dư 1 (số nguyên có dạng 5x + 1) trong phạm vi [1,21].
arr = np.arange(1,22,5)
arr

array([ 1,  6, 11, 16, 21])

In [8]:
# 3.Tạo 1 mảng 1 chiều gồm 11 phần tử cách đều nhau từ 0 đến 1
a = np.linspace(0,1,11,retstep=True)

print(a[0])
# Cho biết khoảng cách giữa các giá trị retstep
print(a[1])

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
0.1


In [9]:
# 4.Tạo 1 mảng 1 chiều gồm 5 phần tử là các số nguyên ngẫu nhiên từ 1 đến 20
np.random.seed(5)
arr = np.random.randint(1,21,5)
arr

array([ 4, 15, 16,  7, 17], dtype=int32)

In [ ]:
# 5.Tạo mảng numpy 1 chiều chứa 10 phần tử với các phần tử ở index chẵn là 0 và ở index lẻ là số lẻ


In [ ]:
# 6.Tạo 1 mảng 1 chiều gồm 10 phần tử có các phần tử ở index [0,3,6,9] là 3 và các phần tử còn lại là 1 


In [12]:
# 7. Tạo 1 mảng 1 chiều gồm 5 phần tử là các giá trị ngẫu nhiên (không trùng nhau) chia hết cho 3 và nhỏ hơn 30
np.random.seed(5)
# Tạo mảng gồm các phần tử nhỏ hơn 30 và chia hết cho 3
arr = np.arange(0,30,3)
# Tạo mảng gồm 5 phần tử ngẫu nhiên (không trùng nhau) từ mảng vừa tạo
a1 = np.random.choice(arr,5,replace=False)
a1

array([27, 15,  6, 12, 21])

### Tạo mảng 2 chiều

In [3]:
# 8.Tạo mảng 2 chiều (3x4) arr_2d với các số chẵn ngẫu nhiên (không trùng nhau) < 50
np.random.seed(1)
arr = np.arange(0,50,2)
arr_2d = np.random.choice(arr,(3,4),replace=False)
arr_2d

array([[28, 26, 34,  6],
       [42, 20, 36, 38],
       [ 8,  4, 40, 12]])

In [5]:
# 9. Tạo một mảng numpy 2 chiều (6x6) với các giá trị biên là 1 và các giá trị còn lại là 0
# Tạo một mảng 2 chiều (6x6) với tất cả giá trị là 1
arr = np.ones((6,6),dtype=int)
arr[1:-1,1:-1] = 0
arr

array([[1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1]])

In [7]:
# 10. Tạo một mảng numpy 2 chiều (3x3) với các giá trị trên đường chéo chính là 1 và các giá trị còn lại là 0 
arr = np.ones(3)
np.diag(arr)
# mảng kết quả


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Phần 2: Truy xuất
### Mảng 1 chiều
Từ mảng even_numbers đã tạo ở câu 1. Hãy thực hiện các truy xuất sau:

In [13]:
even_numbers

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [14]:
# 11. Truy xuất giá trị phần tử thứ 3 của mảng even_numbers
even_numbers[3]

np.int64(8)

In [15]:
# 12. Truy xuất các phần tử từ vị trí thứ 2 đến vị trí thứ 4 (bao gồm cả vị trí thứ 4) của mảng even_numbers
even_numbers[2:5]

array([ 6,  8, 10])

In [16]:
# 13.Truy xuất các phần tử lớn hơn 10 từ mảng even_numbers
even_numbers[even_numbers > 10]

array([12, 14, 16, 18, 20])

In [17]:
# 14. Truy xuất các phần tử chia hết cho 3 từ mảng even_numbers và lớn hơn 10
even_numbers[(even_numbers > 10) & (even_numbers %3==0)]

array([12, 18])

### Mảng 2 chiều
Từ mảng arr_2d đã tạo ở câu 8. Hãy thực hiện các truy xuất sau:

In [9]:
arr_2d

array([[28, 26, 34,  6],
       [42, 20, 36, 38],
       [ 8,  4, 40, 12]])

In [10]:
# 15.Cho biết phần tử ở hàng thứ 2 và cột thứ 3 của mảng arr_2d
arr_2d[2,3]

np.int64(12)

In [11]:
# 16. Hiển thị toàn bộ hàng 1 của mảng arr_2d
arr_2d[1]

array([42, 20, 36, 38])

In [12]:
# 17. Hiển thị toàn bộ cột 2 của mảng arr_2d
arr_2d[:,2]

array([34, 36, 40])

In [13]:
# 18. Lọc các phần tử trong mảng arr_2d lớn hơn 30
arr_2d[arr_2d>30]

array([34, 42, 36, 38, 40])

In [14]:
# 19. Lọc ra các dòng có phần tử ở cột thứ 2 trong mảng arr_2d chia hết cho 4
arr_2d[arr_2d[:,2] % 4 == 0]

array([[42, 20, 36, 38],
       [ 8,  4, 40, 12]])

In [15]:
# 20. Cho biết các giá trị trong mảng arr_2d nằm trong khoảng từ [10, 30]
arr_2d[(arr_2d>=10) & (arr_2d<=30)]

array([28, 26, 20, 12])

## Phần 3: Thêm, xóa, sửa phần tử trong mảng
### Mảng 1 chiều
Từ mảng even_numbers đã tạo ở câu 1. Hãy thực hiện các yêu cầu sau:

In [ ]:
# 21. Thêm giá trị 22 vào cuối mảng 


In [ ]:
# 22. Thêm giá trị 30 vào vị trí thứ 5 của mảng


In [ ]:
# 23. Tạo mảng temp là mảng even_numbers đã xóa giá trị tại vị trí thứ 7 


In [ ]:
# 24. Tạo mảng temp là mảng even_numbers đã xóa giá trị 8


In [ ]:
# 25. Thay đổi các giá trị < 10 từ mảng even_numbers thành 10


### Mảng 2 chiều
Từ mảng arr_2d đã tạo ở câu 8. Hãy thực hiện các yêu cầu sau:

In [16]:
arr_2d

array([[28, 26, 34,  6],
       [42, 20, 36, 38],
       [ 8,  4, 40, 12]])

In [17]:
# 26. Thêm hàng mới [10, 16, 20, 24] vào cuối mảng arr_2d
arr_2d = np.concatenate([arr_2d,[[10, 16, 20, 24]]],axis=0)
arr_2d

array([[28, 26, 34,  6],
       [42, 20, 36, 38],
       [ 8,  4, 40, 12],
       [10, 16, 20, 24]])

In [22]:
# 27. Thêm cột mới [50, 60, 70, 80] vào cuối mảng arr_2d
arr_2d = np.c_[arr_2d,[50, 60, 70, 80]]
arr_2d

array([[28, 26, 34,  6, 50],
       [42, 20, 36, 38, 60],
       [ 8,  4, 40, 12, 70],
       [10, 16, 20, 24, 80]])

In [19]:
np.column_stack([arr_2d,[50, 60, 70, 80]])

array([[28, 26, 34,  6, 50],
       [42, 20, 36, 38, 60],
       [ 8,  4, 40, 12, 70],
       [10, 16, 20, 24, 80]])

In [33]:
np.hstack([arr_2d,np.array([50, 60, 70, 80]).reshape(-1,1)])

array([[28, 30, 34, 30, 50, 50],
       [42, 20, 30, 38, 60, 60],
       [ 8,  4, 40, 20, 70, 70],
       [10, 20, 20, 24, 80, 80]])

In [23]:
# 28. Tạo mảng temp là mảng arr_2d đã xóa hàng thứ 2
temp = np.delete(arr_2d,2,axis=0)
temp

array([[28, 26, 34,  6, 50],
       [42, 20, 36, 38, 60],
       [10, 16, 20, 24, 80]])

In [24]:
# 29. Tạo mảng temp là mảng arr_2d đã xóa cột thứ 3
temp = np.delete(arr_2d,3,axis=1)
temp

array([[28, 26, 34, 50],
       [42, 20, 36, 60],
       [ 8,  4, 40, 70],
       [10, 16, 20, 80]])

In [25]:
# 30. Sửa giá trị tại dòng 1, cột 2 thành 30
arr_2d[1,2] = 30
arr_2d

array([[28, 26, 34,  6, 50],
       [42, 20, 30, 38, 60],
       [ 8,  4, 40, 12, 70],
       [10, 16, 20, 24, 80]])

In [27]:
# 31. Sửa các giá trị lớn hơn 10 và nhỏ hơn 20 trong arr_2d thành 20
arr_2d[(arr_2d>10) & (arr_2d<20)] = 20
arr_2d

array([[28, 26, 34,  6, 50],
       [42, 20, 30, 38, 60],
       [ 8,  4, 40, 20, 70],
       [10, 20, 20, 24, 80]])

In [31]:
# 32. Sửa các giá trị nhỏ hơn 30 và không chia hết cho 4 tại dòng đầu tiên trong arr_2d thành 30
arr_2d[0,(arr_2d[0]<30) & (arr_2d[0] % 4 != 0)] = 30
arr_2d

array([[28, 30, 34, 30, 50],
       [42, 20, 30, 38, 60],
       [ 8,  4, 40, 20, 70],
       [10, 20, 20, 24, 80]])

In [28]:
(arr_2d[0]<30) & (arr_2d[0] % 4 != 0)

array([False,  True, False,  True, False])