### Chapter 2 - Exercise 3: Phân tích  chiều cao (height) dựa vào vị trí (position)

**Cho 2 tập tin *heights_2.txt* và _positions.txt_**  
heights_2.txt: chứa dữ liệu về chiều cao của các cầu thủ  
positions.txt: chứa dữ liệu về vị trí thi đấu của các cầu thủ tương ứng  
'GK' (goalkeeper), 'M' (midfield), 'A' (attack) và 'D' (defense)  
(1 cầu thủ sẽ được lưu thông tin chiều cao và vị trí thi đấu ở cùng index)

# Import thư viện

In [1]:
import numpy as np

# Phần 1: Đọc dữ liệu vào mảng

In [2]:
# 1. Đọc dữ liệu chiều cao từ tệp "heights_2.txt"
heights = np.genfromtxt("heights_2.txt", delimiter=',', dtype=int)
heights

array([191, 184, 185, ..., 183, 179, 179])

In [3]:
# 2. Đọc dữ liệu vị trí thi đấu từ tệp "heights_2.txt"
positions = np.genfromtxt("positions.txt", delimiter=',', dtype=str)
positions

array(['GK', 'M', 'A', ..., 'D', 'D', 'M'], dtype='<U2')

In [4]:
# 3. In ra số phần tử trong mảng chiều cao (số cầu thủ)
print(heights.size)

8847


# Phần 2: Truy Xuất Dữ Liệu

In [5]:
# 4. Cho biết chiều cao của cầu thủ đầu tiên trong mảng
heights[0]

191

In [6]:
# 5. Hiển thị vị trí thi đấu của cầu thủ cuối cùng trong mảng
positions[-1]

'M'

In [7]:
# 6. Cho biết chiều cao của tất cả các cầu thủ tiền đạo "A"
A_heights = heights[positions == "A"]
A_heights

array([185, 186, 187, ..., 175, 189, 175])

In [8]:
# 7. Cho biết chiều cao của các thủ môn "GK"
GK_heights = heights[positions == "GK"]
GK_heights[:10]

array([191, 193, 190, 185, 188, 187, 189, 196, 190, 189])

In [9]:
# 8. Cho biết chiều cao của các tiền vệ "M"
M_heights = heights[positions == "M"]
M_heights[:10]

array([184, 181, 170, 179, 183, 185, 170, 188, 175, 170])

In [10]:
# 9. Cho biết chiều cao của các hậu vệ "D"
D_heights = heights[positions == "D"]
D_heights[:10]

array([180, 187, 183, 188, 180, 185, 185, 178, 185, 193])

In [11]:
# 10. Cho biết vị trí thi đấu của các cầu thủ có chiều cao trên 2m
positions[heights> 200]

array(['GK', 'A', 'GK', 'GK', 'A', 'GK', 'GK', 'A', 'GK', 'A', 'A'],
      dtype='<U2')

In [12]:
# 11. Có bao nhiêu thủ môn "GK" cao dưới 1.75m
GK_heights[GK_heights < 175].size

3

In [13]:
# 12. Có bao nhiêu tiền vệ "M" cao trên 1.95m
M_heights[M_heights > 195].size

4

# Phần 3: Thống Kê Dữ Liệu

In [14]:
# 13. Tính chiều cao lớn nhất và nhỏ nhất
max_height = np.max(heights)
min_height = np.min(heights)
print("Chiều cao lớn nhất:", max_height)
print("Chiều cao nhỏ nhất:", min_height)

Chiều cao lớn nhất: 208
Chiều cao nhỏ nhất: 158


In [15]:
# 14. Cho biết chiều cao của 5 cầu thủ cao nhất và 5 cầu thủ thấp nhất
# 5 cầu thủ thấp nhất
np.sort(heights)[:5]

array([158, 160, 160, 160, 160])

In [16]:
# 5 cầu thủ cao nhất
np.sort(heights)[-5:]

array([202, 202, 203, 203, 208])

In [17]:
# 15. Tính chiều cao trung bình của các cầu thủ
np.mean(heights)

181.75042387249914

In [18]:
# 16. Tính độ lệch chuẩn của chiều cao
np.std(heights)

6.45399099502128

In [19]:
# 17. Tính chiều cao lớn nhất và nhỏ nhất của các thủ môn
max_GK = np.max(GK_heights)
min_GK = np.min(GK_heights)
print("Thủ môn cao nhất:", max_GK)
print("Thủ môn thấp nhất:", min_GK)

Thủ môn cao nhất: 208
Thủ môn thấp nhất: 173


In [20]:
# 18. Tính chiều cao lớn nhất và nhỏ nhất của các tiền đạo
max_A = np.max(A_heights)
min_A = np.min(A_heights)
print("Tiền đạo cao nhất:", max_A)
print("Tiền đạo thấp nhất:", min_A)

Tiền đạo cao nhất: 203
Tiền đạo thấp nhất: 160


In [21]:
# 19. Tính chiều cao lớn nhất và nhỏ nhất của các tiền vệ
max_M = np.max(M_heights)
min_M = np.min(M_heights)
print("Tiền vệ cao nhất:", max_M)
print("Tiền vệ thấp nhất:", min_M)

Tiền vệ cao nhất: 196
Tiền vệ thấp nhất: 158


In [22]:
# 20. Tính chiều cao lớn nhất và nhỏ nhất của các hậu vệ
max_D = np.max(D_heights)
min_D = np.min(D_heights)
print("Hậu vệ cao nhất:", max_D)
print("Hậu vệ thấp nhất:", min_D)

Hậu vệ cao nhất: 200
Hậu vệ thấp nhất: 162


In [23]:
# 21. Tính số lượng cầu thủ theo vị trí thi đấu
# Số lượng thủ môn
count = np.sum(positions == "GK")
print(f'Goalkeeper : {count} cầu thủ')

Goalkeeper : 930 cầu thủ


In [24]:
# Số lượng tiền vệ
count = np.sum(positions == "M")
print(f'Midfield : {count} cầu thủ')

Midfield : 3041 cầu thủ


In [25]:
names = ['Goalkeeper', 'Midfield', 'Attack', 'Defense']
codes = ['GK', 'M', 'A', 'D']

In [26]:
print("Số lượng cầu thủ từng vị trí thi đấu:")
for code, name in zip(codes, names):
    count = np.sum(positions == code)
    print(f'- {name} : {count} cầu thủ')

Số lượng cầu thủ từng vị trí thi đấu:
- Goalkeeper : 930 cầu thủ
- Midfield : 3041 cầu thủ
- Attack : 2082 cầu thủ
- Defense : 2794 cầu thủ


In [27]:
# 22. Cho biết chiều cao trung bình của các 'GK' (goalkeeper), 'M' (midfield), 'A' (attack) và 'D' (defense)
# Tính chiều cao trung bình của các thủ môn GK.
average_height = heights[positions == "GK"].mean()
print(f'Goalkeeper : {round(average_height, 2)}cm')

Goalkeeper : 188.23cm


In [28]:
# Tính chiều cao trung bình của các tiền đạo "A".
average_height = heights[positions == "A"].mean()
print(f'Attack : {round(average_height, 2)}cm')

Attack : 180.94cm


In [29]:
# 23. Cho biết chiều cao trung bình của các 'GK' (goalkeeper), 'M' (midfield), 'A' (attack) and 'D' (defense)
print("Chiều cao trung bình của từng vị trí thi đấu:")
for code, name in zip(codes, names):
    average_height = heights[positions == code].mean()
    print(f'- {name}: {round(average_height, 2)}cm')

Chiều cao trung bình của từng vị trí thi đấu:
- Goalkeeper: 188.23cm
- Midfield: 179.04cm
- Attack: 180.94cm
- Defense: 183.15cm
